CREATE TABLE tradesman_resume (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
user_id INT UNSIGNED NOT NULL,
specialty VARCHAR(255) NULL,
profile_pic VARCHAR(255) NULL,
about_me TEXT NULL,
prefered_work_location VARCHAR(255) NULL,
work_fee INT NULL,
certificate VARCHAR(255) NULL,
valid_id_front VARCHAR(255) NULL,
valid_id_back VARCHAR(255) NULL,
tradesman_full_name VARCHAR(255) NULL,
status_of_approval ENUM('Pending','Declined','Approved') NULL,
is_active TINYINT(1) NOT NULL,
is_approve TINYINT(1) NOT NULL,
updated_at  DATETIME NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE = InnoDB;