CREATE TABLE jobs (
id INT UNSIGNED AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
client_fullname VARCHAR(255) NOT NULL,
client_profile_picture VARCHAR(255) NULL,
salary DECIMAL(10,2) NOT NULL,
job_type ENUM(
'carpenter',
'painter',
'welder',
'electrician',
'plumber',
'mason',
'roofer',
'ac_technician',
'mechanic',
'drywaller',
'cleaner'
) NOT NULL,
job_description TEXT NOT NULL,
location TEXT NOT NULL,
latitude DECIMAL(9,6) NULL,
longitude DECIMAL(9,6) NULL,
status ENUM('available','ongoing','done') NOT NULL,
deadline DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
INDEX idx_job_type (job_type),
INDEX idx_location_coords (latitude, longitude)
) ENGINE = InnoDB;