CREATE TABLE job_applications (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
resume_id INT UNSIGNED NOT NULL,
job_id INT UNSIGNED NOT NULL,
client_id INT UNSIGNED NOT NULL,
client_fullname VARCHAR(255) NOT NULL,
tradesman_fullname VARCHAR(255) NOT NULL,
tradesman_profile_picture VARCHAR(255) NOT NULL,
client_profile_picture VARCHAR(255) NOT NULL,
job_address VARCHAR(255) NOT NULL,
job_type ENUM('Carpentry','Painter','Welding','Electrical_work','Plumbing','Masonry','Roofing','Ac_Repair','Mechanic','Cleaning'),
job_deadline DATE NOT NULL,
qualification_summary TEXT NOT NULL,
status ENUM('Pending','Active','Declined','Completed','Failed','Cancelled'),
cancelled_reason TEXT NULL,
cancelled_by ENUM('Client','Tradesman') NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
job_date_status DATE NULL,
created_at DATE NOT NULL,
INDEX (`user_id`),
INDEX (`resume_id`),
INDEX (`job_id`),
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (resume_id) REFERENCES tradesman_resume(id),
FOREIGN KEY (job_id) REFERENCES jobs(id)
) ENGINE = InnoDB;

