CREATE TABLE ratings(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tradesman_id INT UNSIGNED NOT NULL,
client_id INT UNSIGNED NOT NULL,
profile VARCHAR(255) NULL,
ratings INT NOT NULL,
message VARCHAR(500) NOT NULL,
client_name VARCHAR(255) NOT NULL,
rated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
FOREIGN KEY (tradesman_id) REFERENCES client_booking(tradesman_id) ON DELETE CASCADE,
FOREIGN KEY (client_id) REFERENCES client_booking(user_id) ON DELETE CASCADE
)ENGINE = InnoDB;