CREATE TABLE ratings(
id INT UNSIGNED AUTO_INCREMENT,
tradesman_id INT UNSIGNED NOT NULL,
client_id INT UNSIGNED NOT NULL,
profile VARCHAR(255) NOT NULL,
ratings INT NOT NULL,
message VARCHAR(500) NOT NULL,
client_name VARCHAR(255) NOT NULL,

)