CREATE TABLE forgot_password_admin(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
email VARCHAR(255) NOT NULL,
token VARCHAR(15) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES admin(id) ON DELETE CASCADE
):ENGINE = InnoDB;