CREATE TABLE users (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
username VARCHAR(100) NOT NULL UNIQUE,
birthdate DATE NOT NULL ,
suspend TINYINT(1) NOT NULL,
email_verified_at DATE NULL,
email VARCHAR(255) NOT NULL UNIQUE,
profile VARCHAR(255) NULL,
is_client TINYINT(1) NULL,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB;

